export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const CHANGE_USER_STUDENT = 'CHANGE_USER_STUDENT'
export const CHANGE_USER_TEACHER = 'CHANGE_USER_TEACHER'
// export const NEW_POST = 'NEW_POST'
// export const ADD = 'ADD'
// export const SUBTRACT = 'SUBTRACT'
// export const FORM = 'FORM'
